### ISSUE TITLE
编译提示头文件找不到

### ISSUE THREAD

**Issue by liugang1104** [DSAppTeam/cocoapods-project-hmap#10]
PodA 中依赖 PodB

头文件导入方式： #import <PodB/PodB.h>

使用 hmap print PodA.hmap 打印PodA的 hmap :
PodB-iOS/PodB.h:  xxxx
PodB.h: xxxx
会多一个-iOS的后缀。

我尝试将头文件引用修改为 #import <PodB-iOS/PodB.h> ，通过cmd+鼠标左键 可以正常跳转到 PodB.h

**Comment by chenxGen** [comment]
这个应该是 module_name 和 target_name 不一致的情况，我记得两种情况都是有处理的，晚上看下

**Comment by chenxGen** [comment]
你用的什么版本 我这边测试没啥问题

**Comment by chenxGen** [comment]
过很长时间没有提供更多的信息，并且没有复现该问题，先关闭了，有问题再联系
