### ISSUE TITLE
编译失败——'JPush/JPUSHService.h' file not found

### ISSUE THREAD

**Issue by huntingcat** [DSAppTeam/cocoapods-project-hmap#3]
都按着流程处理，不过就是有一个一直编译失败

/Users/hyk/JuYing-iOS/JYVIP/JYVIP-Bridging-Header.h:49:9: error: 'JPush/JPUSHService.h' file not found
#import <JPush/JPUSHService.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/hyk/Library/Developer/Xcode/DerivedData/JYVIP-aqlnptmruajmcxakdgjvjhfgcddk/Build/Intermediates.noindex/PrecompiledHeaders/JYVIP-Bridging-Header-swift_36G6FXDKB0YHP-clang_33A5QUT1UCGWU.pch' for bridging header '/Users/hyk/JuYing-iOS/JYVIP/JYVIP-Bridging-Header.h'
2 errors generated.

**Comment by huntingcat** [comment]
![image](https://user-images.githubusercontent.com/3232800/118920857-bf78c600-b969-11eb-9b6c-a02fc7f73f59.png

**Comment by huntingcat** [comment]
![未命名](https://user-images.githubusercontent.com/3232800/118920958-e7682980-b969-11eb-8985-a5707fffb48b.png)

**Comment by chenxGen** [comment]
修复了 麻烦升级一下插件
