### ISSUE TITLE
是不是没有考虑到application extension

### ISSUE THREAD

**Issue by YaoJuan** [DSAppTeam/cocoapods-project-hmap#4]
例如我们项目中有一个today widget。执行podinstall之后文件里的一些import直接找不到文件。

**Comment by chenxGen** [comment]
这是个通用方案哦，我们项目中也有一些app extension，没问题的，你检查下你们extension对应那个target的OTHER C FLAGS有没有 $(inherited) ？

**Comment by YaoJuan** [comment]
> 这是个通用方案哦，我们项目中也有一些app extension，没问题的，你检查下你们extension对应那个target的OTHER C FLAGS有没有 $(inherited) ？

无，是应该有吗

**Comment by chenxGen** [comment]
是的 不然无法继承xcconfig的配置

**Comment by chenxGen** [comment]
如果你的项目有用swift的话，OTHER SWIFT FLAGS也要加一下 @YaoJuan

**Comment by YaoJuan** [comment]
> 如果你的项目有用swift的话，OTHER SWIFT FLAGS也要加一下 @YaoJuan

还是不行，我设置完了之后执行pod install之后other c flags都指向了新生成的hmap

**Comment by YaoJuan** [comment]
> 如果你的项目有用swift的话，OTHER SWIFT FLAGS也要加一下 @YaoJuan

请问这个是通过我的library search path里面添加的库来生成对应的hmap吗？

**Comment by chenxGen** [comment]
具体是哪个头文件找不到呢，贴下你编译失败哪个文件的编译指令，以及在项目根目录执行`hmap print Pods/$NAME.hmap | grep $HEADER`，NAME为你Pods目录生成的hmap文件名，HEADER 为提示未找到的header，看下有无对应的记录

**Comment by YaoJuan** [comment]
> 具体是哪个头文件找不到呢，贴下你编译失败哪个文件的编译指令，以及在项目根目录执行`hmap print Pods/$NAME.hmap | grep $HEADER`，NAME为你Pods目录生成的hmap文件名，HEADER 为提示未找到的header，看下有无对应的记录

编译到这个application extension 其中.m文件import<xxxprivatepod/xxxprivatepod.h>那一行出错，由于公司原因，不能说出具体库，抱歉，是一个私有库

fatal error: 'xxxprivatepod/xxxprivatepod.h' file not found

用grep来查确实里面没有这个头文件

**Comment by chenxGen** [comment]
因为插件本身的策略是仅仅会针对public header生成hmap，所以很有可能你的xxxprivatepod在podspec中没有声明为public header，如`s.public_header_files = 'xxxprivatepod.h'`，但是如果这样的话你们之前build应该也会失败的，是不是手动加了什么header search path 路径去兼容？

**Comment by YaoJuan** [comment]
> 因为插件本身的策略是仅仅会针对public header生成hmap，所以很有可能你的xxxprivatepod在podspec中没有声明为public header，如`s.public_header_files = 'xxxprivatepod.h'`，但是如果这样的话你们之前build应该也会失败的，是不是手动加了什么header search path 路径去兼容？

确实如你所言，私有库没有写public，然后header search path加了兼容。那我是不是应该好好整顿一下这些私有库才用这个插件比较好

**Comment by chenxGen** [comment]
> > 因为插件本身的策略是仅仅会针对public header生成hmap，所以很有可能你的xxxprivatepod在podspec中没有声明为public header，如`s.public_header_files = 'xxxprivatepod.h'`，但是如果这样的话你们之前build应该也会失败的，是不是手动加了什么header search path 路径去兼容？
> 
> 确实如你所言，私有库没有写public，然后header search path加了兼容。那我是不是应该好好整顿一下这些私有库才用这个插件比较好

嗯 原则上开发第三方库的时候需要声明好header的适用范围，防止内部业务出错，同时简化使用

**Comment by chenxGen** [comment]
想了下 有些时候这些情况不可避免，所以我打算加一个白名单
