### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by zhangjiemin000** [DSAppTeam/cocoapods-project-hmap#5]
作者你好，我们项目中引入之后，编译报错，如图所示，请问是为什么呢？
![image](https://user-images.githubusercontent.com/35087172/119596764-5e8e3980-be12-11eb-88ee-eb0dee01a32e.png)

**Comment by chenxGen** [comment]
你IGListKit的版本是啥，看错误提示怎么像是你IGListAdapter.h 这个public header中用了`#import "IGListExperiments.h"`，而不是`#import <IGListDiffKit/IGListExperiments.h>`

**Comment by zhangjiemin000** [comment]
![image](https://user-images.githubusercontent.com/35087172/119605090-c51b5380-be22-11eb-9182-91546073304a.png)

![image](https://user-images.githubusercontent.com/35087172/119605138-d82e2380-be22-11eb-9504-4856d8d280ad.png)

看起来是用的 
#import <IGListDiffKit/IGListExperiments.h>
请问我可以从哪个方面来排查呢？

**Comment by chenxGen** [comment]
> 作者你好，我们项目中引入之后，编译报错，如图所示，请问是为什么呢？
> ![image](https://user-images.githubusercontent.com/35087172/119596764-5e8e3980-be12-11eb-88ee-eb0dee01a32e.png)

我上面的理解有误，可以先忽略，你这里错误日志中的#import "IGListAdapter"是写在哪里的？截图上下文有么？
