### ISSUE TITLE
冲突

### ISSUE THREAD

**Issue by panshimin** [DSAppTeam/cocoapods-project-hmap#6]
![image](https://user-images.githubusercontent.com/7685633/121337634-54f6ec80-c94f-11eb-8940-d0eebe2c81c8.png)

**Comment by chenxGen** [comment]
应该是cocoapods版本兼容性问题，你的cocoapods什么版本的？

**Comment by chenxGen** [comment]
现在还没兼容1.6.0，你升级cocoapods到1.10.1

**Comment by panshimin** [comment]
感觉是和项目中，其他使用 install_hooks 的冲突了，我试试 cocospods 1.10.1

**Comment by chenxGen** [comment]
最新代码已兼容到cocoapods 1.7.0版本了

**Comment by chenxGen** [comment]
@panshimin 更新能解决你的问题么？

**Comment by chenxGen** [comment]
插件最低只能支持到 cocoapods 1.7.0 ，已测试； issue 无回复先关闭了。
