### ISSUE TITLE
动态库使用报错

### ISSUE THREAD

**Issue by design1890** [DSAppTeam/cocoapods-project-hmap#8]
你好, 我在组件库中使用依赖CropViewController, 并且podspec中s.static_framework=true,  然后在podfile中使用use_frameworks!,  引入#import CropViewController 头文件, CropViewController库中会提示重复命名错误.  我在你提供的demo中动态库引入, 然后使用swift依赖头文件也会报错. 除此之外我们在其他库也会有不同的报错. 方便加wx: zydyrxbsbfl804129187 或者qq: 804129187吗

**Comment by chenxGen** [comment]
收到了你的问题，解决中，有结论再和你同步哈。

**Comment by design1890** [comment]
好的, 非常感谢
