### ISSUE TITLE
hmap使用问题  

### ISSUE THREAD

**Issue by kakao6** [DSAppTeam/cocoapods-project-hmap#9]
``platform :ios, '9.0'
plugin 'cocoapods-project-hmap'
turn_prebuilt_hmap_off_for_pod_targets
inhibit_all_warnings!

swift_pod_names = ['Moya', 'ObjectMapper', 'SwiftyJSON', 'PromiseKit', 'Alamofire']

只需要 执行  plugin 'cocoapods-project-hmap'  和 turn_prebuilt_hmap_off_for_pod_targets 这两句代码，然后pod install  就可以了吗

**Comment by chenxGen** [comment]
QQ 沟通过了

**Comment by linfei2222** [comment]
target 'testRn' do
  plugin 'cocoapods-hmap-prebuilt'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for testRn
  pod 'MFSCache', '2.0.1'
  pod 'AFNetworking','= 4.0.1'
  pod 'JSONModel','= 1.8.0'
  pod 'MJExtension','= 3.2.1'


end

执行了，没变化，没有生成对应的hmap
